# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/production/vault.yml

wordpress_sites:

  affinitymws.com:
    site_hosts:
      - canonical: affinitymws.com
        redirects:
          - www.affinitymws.com
    local_path: ../affinitymws.com # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:affinitymwsolutions/affinitymws.com.git # replace with your Git repo URL
    branch: master
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: false

  tammychau.com:
    site_hosts:
      - canonical: tammychau.affinitymws.com
        redirects:
          - www.tammychau.affinitymws.com
    local_path: ../tammychau.com # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:affinitymwsolutions/tammychau.com.git # replace with your Git repo URL
    branch: master
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: false

  cannabisriskconsulting.com:
    site_hosts:
      - canonical: cannabisriskconsulting.affinitymws.com
        redirects:
          - www.cannabisriskconsulting.affinitymws.com
    local_path: ../cannabisriskconsulting.com # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:affinitymwsolutions/cannabisriskconsulting.com.git # replace with your Git repo URL
    branch: master
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: false
